### ISSUE TITLE
Character sprite changing when turning

### ISSUE THREAD

**Issue by thedrummeraki** [brandonbrule/_Overview#4]
Hello @brandonbrule! Great project! I just found something interesting when you try to move diagonally. When the sprite updates, I believe on `Update()`, the game object tries to understand whether or not the user wants to go `up` or `down`, `left` or `right`. I wasn't able to locate where this happens, so I'll have a look tonight after work.

Are there any sprites showing diagonal movement created at the moment? If not, I would like to submit a temporary fix involving only choosing a sprite when going diagonally (ie: `up` or `down`, `left` or `right`). This would of course not affect the character's movements. I don't know how this would like, so I'd like to give that a try and hope it doesn't look awkward. Any thoughts?

In the event when such sprites are designed, this fix will hopefully help for updating the character sprite the right way.

I'm currently having this issue myself in a game I'm trying building so I may have a way or two to fix this!

**Comment by brandonbrule** [comment]
Hey Aki!

Let me make a commit tonight. I've redone the way the animations are called.

http://brandonbrule.com/00/overview/03/  [playable demo]

The answer to this is to run all the logic itself through an [animator controller](https://docs.unity3d.com/Manual/class-AnimatorController.html) and blend the states together.  

Here's a great video that helped me understand this better.

https://www.youtube.com/watch?v=XZDjkQ8wEd0

**Comment by thedrummeraki** [comment]
Yes I've heard of Animation controllers and actually am discovering them at work! I'll take a look at it and looking forward to the commit!

**Comment by thedrummeraki** [comment]
Neat! I just checked out the new update, and I really like what the animators can do. @brandonbrule Looks like this issue is resolved, I'll let you know if I find anything interesting to look at.

**Comment by brandonbrule** [comment]
Sweet! Let me know if you want to have a google hangout and I can show you how its setup.
